### ISSUE TITLE
When will the code be open sourced?

### ISSUE THREAD

**Issue by gbyy422990** [zhangzw12319/lcps#1]

**Comment by zhangzw12319** [comment]
Thanks for your attention. Code will come soon.
Since we did not use framework such as OpenMMLab serires at beginning, our implementation contains lots of redundancy segments and is kind of uneasy for readerd to read. We are cleaning, smplifying and reorganizing the folder and code structure, which will cost a period of time.
We expect the legal approval will finish in the next couple of weeks and please keep notified.
