### ISSUE TITLE
Issues about training batch size

### ISSUE THREAD

**Issue by zhangguanghui1** [zhangzw12319/lcps#11]
Thank you very much for the excellent work.
I would like to confirm if this set of settings is feasible. 
![微信截图_20240406211417](https://github.com/zhangzw12319/lcps/assets/28031977/10555ac6-0c0a-4fc8-bc66-d0c8e3f984e9)
When I tried batch size=2, it reported an error of out of memory. I don't know where the parameter setting problem is, right? 
**pa_po_nuscenes_trainval.yaml:**
dataset:
    name: nuscenes
    version: v1.0-trainval
    path: ../data/nuscenes
    sample_pkl_path: ../data/nuscenes/pkl_files
    rotate_aug: True
    flip_aug: True
    max_volume_space: [ 100, 3.1415926, 3 ]
    min_volume_space: [ 0, -3.1415926, -5 ]dataset:
    name: nuscenes
    version: v1.0-trainval
    path: ../data/nuscenes
    sample_pkl_path: ../data/nuscenes/pkl_files
    rotate_aug: True
    flip_aug: True
    max_volume_space: [ 100, 3.1415926, 3 ]
    min_volume_space: [ 0, -3.1415926, -5 ]
    gt_generator:
        sigma: 5
    grid_size: [480, 360, 32] 
    inst_aug:
        if_use: False
        aug_type: contmix
        inst_pkl_path: ../data/nuscenes/instance_database_train/inst_database_train_info.pkl 
        inst_trans: True # random translation for contmix
        inst_rotate: True
        inst_flip: True
        inst_add: True
    num_worker: 1 # 4 
    min_points: 15  # 15 
model:
    pix_fusion: True
    pix_fusion_path: ../checkpoints/resnet18-5c106cde.pth 
    use_sara: True
    use_att: True
    model_load_path: null
    model_save_path: ./nu_8k2b4l.pt
    train_batch_size: 2 
    val_batch_size: 2
    learning_rate: 0.004
    LR_MILESTONES: [40, 150, 200]  # [100, 150, 200]
    LR_GAMMA: 0.5
    check_iter: 4000
    max_epoch: 300
    post_proc:
        threshold: 0.1
        nms_kernel: 5
        top_k: 100
    center_loss: MSE
    offset_loss: L1
    center_loss_weight: 100
    offset_loss_weight: 10

Thanks.

**Comment by zhangzw12319** [comment]
My current suggestion is that you can try run on single 3090/4090 GPU with `batchsize=2` and `num_worker=1`. Since DDP also consumes GPU memory. The time cost is approximately 3.5h/Epoch, which can be trained for demo experiments. Or you can choose 32G V100 or 48G A6000/A40 for stable training.

The behavior of GPU memory consumption is kind of strange actually, because I found that it's a machine-dependent factor. When I conducted experiments on my school lab server it could just be narrowed into 24G memory with `batch-size=2` and `num_worker=1` with 2 GPUs parallel-training. However, when I rent GPU on  AutoDL，it raised OOM error and I had to rent V100 or A40 GPU. And I tried to borrow other labs' 24G GPU device and also raised OOM error. So if you find 24G cannot fit, it is better to use V100 32G for stable training. 

The most ideal training setting is using 8 x A40 GPUs with `batch-size=2`，with each GPU using 30~38G memory.

**Comment by zhangguanghui1** [comment]
Thank you for your reply, which solves my doubts. Thanks. @zhangzw12319
