### ISSUE TITLE
some doubt about Asynchronous Compensation Pixel Alignment?

### ISSUE THREAD

**Issue by AndyYuan96** [zhangzw12319/lcps#2]
Hi, thanks for sharing the great paper. I just wonder that does ACPA is not a normal operation? as for multimodal detection, when prepare training data, we will consider the asynchronous problem, it a very common operation that will do in many codebase like mmdetection3d 、centerpoint。or it's not a common operation in Panoptic Segmentation? And I don't see ablation study about ACPA, only ACPA with other module.

**Comment by zhangzw12319** [comment]
Thanks for your attention. Previous object detection or semantic segmentation methods such as PointPainting, PointAugmenting and IMF mostly directly align each lidar frame with the images at the closest timestamp, while our ACPA aims at transforming the 3D coordinate into a new position at the time when images are captured. Detailedly, we decompose such transformation into the combination of  two sub transformations. Furthermore, different from detection settings, panoptic segmentation needs more low-level discrminative features in multi-modal fusion to better recognize point-level instance information. 

For ablation study, it can be observed that our ACPA improves PQ performance contrasting the first two lines of Table 3. Please note that SC represents simple concantenation and it is not a another proposed module, since LiDAR-only baseline do not need point-pixel feature concatenation. Moreover, we provide qualitative comparisons of ACPA in Figure 7 of the Appendix。

**Comment by AndyYuan96** [comment]
> Thanks for your attention. Previous object detection or semantic segmentation methods such as PointPainting, PointAugmenting and IMF mostly directly align each lidar frame with the images at the closest timestamp, while our ACPA aims at transforming the 3D coordinate into a new position at the time when images are captured. Detailedly, we decompose such transformation into the combination of two sub transformations. Furthermore, different from detection settings, panoptic segmentation needs more low-level discrminative features in multi-modal fusion to better recognize point-level instance information.
> 
> For ablation study, it can be observed that our ACPA improves PQ performance contrasting the first two lines of Table 3. Please note that SC represents simple concantenation and it is not a another proposed module, since LiDAR-only baseline do not need point-pixel feature concatenation. Moreover, we provide qualitative comparisons of ACPA in Figure 7 of the Appendix。

1. I know how you do ACPA，as I’m familiar with multi-modal 3d object detection，when find point-image corresponding relation，In nuScenes，we will first convert point cloud to global coordinate and then transform into the ego vehicle frame for the timestamp of the image，and I thought the operation is a default operation for multi modal method。
2. I think you can give a result that only concatenation is used to say that ACPA is useful，rather than ACPA with concatenation。

**Comment by zhangzw12319** [comment]
Well, it may not be a default operation as a common concept in my understanding, as you can see that direct projection without step-2 and step-3 of ACPA in Figure 7 usually cause some misalignment in the edges as previous approaches do. It is not so good but can be still used. When adding asynchronous compensation, the misalgnment is refined. Also, more accurate projection is important for the following fusion module.

Moreover, thanks for you second advice and we will consider more experiments settings to dig deeper. Quantitatively, our ACPA has showned performance improvement and proved the usefulness. And my initial thought is that you have to firstly decide which pixels in which camera to be aligned, then you can fuse/concatenate them together, and thus concatenation is naturally accompanied with ACPA. We will pay attention to more experiments design.
