### ISSUE TITLE
How to  extract lidarseg  and panoptic dataset of nuScene?

### ISSUE THREAD

**Issue by the-king-of-yhq** [zhangzw12319/lcps#5]
How to  extract lidarseg  and panoptic dataset of nuScene? Thank you for your reply.

**Comment by zhangzw12319** [comment]
You can download NuScenes lidarseg dataset GT from [here](https://www.nuscenes.org/lidar-segmentation) and panoptic dataset GT from [here](https://www.nuscenes.org/panoptic). Then, organize the dataset as [doc](https://github.com/zhangzw12319/lcps/blob/main/docs/prepare_nusc.md) specifies. Hope this can fix your question.

**Comment by the-king-of-yhq** [comment]
File "/home/star/sharedata/yhq/lcps-main/dataloader/dataset.py", line 367, in __getitem__
    self.nusc.get('lidarseg', lidar_sd_token)['filename'])
  File "/home/star/sharedata/tzy/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py", line 169, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table lidarseg not found

**Comment by the-king-of-yhq** [comment]
How can I address it

**Comment by the-king-of-yhq** [comment]
File "/home/star/sharedata/yhq/lcps-main/dataloader/dataset.py", line 367, in __getitem__
    self.nusc.get('lidarseg', lidar_sd_token)['filename'])
  File "/home/star/sharedata/tzy/nuscenes-devkit/python-sdk/nuscenes/nuscenes.py", line 169, in get
    assert table_name in self.table_names, "Table {} not found".format(table_name)
AssertionError: Table lidarseg not found
How can I address it?

**Comment by zhangzw12319** [comment]
`Table lidarseg not found` means that your meta file for `lidarseg` is not correctly placed. I suppose that the `lidarseg.json` file is missing in directory `xxx/v1.0-trainval/lidarseg.json`. Please check whether your `lidarseg.json`, `panoptic.json` and other necessary json meta files are in `xxx/v1.0-trainval` , `xxx/v1.0-mini` if you want to load `v1.0-trainval` and `v1.0-mini` correctly.

You can follow the dataset structure as [doc](https://github.com/zhangzw12319/lcps/blob/main/docs/prepare_nusc.md) strictly and check whether all meta files are in the supposed directory. Further detailed instructions are provided in NuScenes lidarseg competition [here](https://www.nuscenes.org/lidar-segmentation) and panoptic competition [here](https://www.nuscenes.org/panoptic).

**Comment by the-king-of-yhq** [comment]
Thank you. I overwrite nuscenes.py to address it.

**Comment by zhangzw12319** [comment]
:)

**Comment by the-king-of-yhq** [comment]
Sorry,  I  want to  ask this reason for None during training?
alidation per class PQ, SQ, RQ and IoU: 
             barrier :   0.00%    0.00%    0.00%    0.00%
             bicycle :   0.00%    0.00%    0.00%    0.00%
                 bus :   0.00%    0.00%    0.00%    0.00%
                 car :   0.00%    0.00%    0.00%    0.00%
construction_vehicle :   0.00%    0.00%    0.00%    0.00%
          motorcycle :   0.00%    0.00%    0.00%    0.00%
          pedestrian :   0.00%    0.00%    0.00%    0.00%
        traffic_cone :   0.00%    0.00%    0.00%    0.00%
             trailer :   0.00%    0.00%    0.00%    0.00%
               truck :   0.00%    0.00%    0.00%    0.00%
   driveable_surface :   0.00%    0.00%    0.00%    0.00%
          other_flat :   0.00%    0.00%    0.00%    0.00%
            sidewalk :   0.00%    0.00%    0.00%    0.00%
             terrain :   0.00%    0.00%    0.00%    0.00%
             manmade :   0.00%    0.00%    0.00%    0.00%
          vegetation :   0.00%    0.00%    0.00%    0.00%
PQ 0.0  PQ_dagger  0.0  SQ 0.0  RQ 0.0  |  PQ_th 0.0  SQ_th 0.0  RQ_th 0.0  |  PQ_st 0.0  SQ_st 0.0  RQ_st 0.0  |  mIoU 0.0
Current val PQ is 0.0 while the best val PQ is 66.2
Current val miou is 0.0
epoch 29 iter  4688, avg_loss: nan, semantic loss: 0.4, center loss: 0.7, offset loss: 0.1, instmap loss: 0.7, pix loss: 2.6

Validation per class iou: 
barrier : 1.08%
bicycle : 0.00%
bus : 0.00%
car : 0.00%
construction_vehicle : 0.00%
motorcycle : 0.00%
pedestrian : 0.00%
traffic_cone : 0.00%
trailer : 0.00%
truck : 0.00%
driveable_surface : 0.00%
other_flat : 0.00%
sidewalk : 0.00%
terrain : 0.00%
manmade : 0.00%
vegetation : 0.00%
Current val miou is 0.1
epoch: 30   lr: 0.00400

**Comment by zhangzw12319** [comment]
It's strange because it says `while the best val PQ is 66.2`, but it suddenly reduces to zero in the middle epoch.
Some suggestions:
1. You can load my released weights on NuScenes and just do evaluation to see whether the performance can be achieved. If so, the network structure of my released code shoulde be fine.
2. You can compare the PQ and mIoU calculation process between my released weights, your 66.2 PQ weights and your current zero PQ weights. Debug the code of evaluation part and find reasons.
3.  If it's convenient, you can upload your training logs and share links from cloud drive such as Baidu Cloud so that I can see your full training log.(It is too long, no recommendation for just paste the full log in the comment)

**Comment by the-king-of-yhq** [comment]
https://pan.baidu.com/s/1pqn4GrZCWvcOvSALygCqjQ?pwd=tkpk
Can you see

**Comment by zhangzw12319** [comment]
OK, I've seen your report and I will check it out. Yet, I've been really busy for several projects recently and the process may spend a period of time. You can also check by yourself according to my first two suggestions by line-wise debugging (I'll also do it in the meanwhile)

**Comment by the-king-of-yhq** [comment]
Thank you

**Comment by the-king-of-yhq** [comment]
Sorry, I use your wights to get this results
Validation per class PQ, SQ, RQ and IoU: 
             barrier :   0.00%    0.00%    0.00%    0.00%
             bicycle :   0.00%    0.00%    0.00%    0.00%
                 bus :   0.00%    0.00%    0.00%    0.00%
                 car :   0.00%    0.00%    0.00%    0.00%
construction_vehicle :   0.00%    0.00%    0.00%    0.00%
          motorcycle :   0.00%    0.00%    0.00%    0.00%
          pedestrian :   0.00%    0.00%    0.00%    0.00%
        traffic_cone :   0.00%    0.00%    0.00%    0.00%
             trailer :   0.00%    0.00%    0.00%    0.00%
               truck :   0.00%    0.00%    0.00%    0.00%
   driveable_surface :   0.00%    0.00%    0.00%    0.00%
          other_flat :   0.00%    0.00%    0.00%    1.34%
            sidewalk :   0.00%    0.00%    0.00%    0.00%
             terrain :   0.00%    0.00%    0.00%    0.00%
             manmade :   0.00%    0.00%    0.00%    0.00%
          vegetation :   0.00%    0.00%    0.00%    0.00%
PQ 0.000  PQ_dagger  0.000  SQ 0.000  RQ 0.000  |  PQ_th 0.000  SQ_th 0.000  RQ_th 0.000  |  PQ_st 0.000  SQ_st 0.000  RQ_st 0.000  |  mIoU 0.084
Current val PQ is 0.000
Current val miou is 0.084
Validation per class iou: 
barrier : 0.00%
bicycle : 0.00%
bus : 0.00%
car : 0.00%
construction_vehicle : 0.00%
motorcycle : 0.19%
pedestrian : 0.00%
traffic_cone : 0.00%
trailer : 0.00%
truck : 0.00%
driveable_surface : 0.00%
other_flat : 1.33%
sidewalk : 0.00%
terrain : 0.00%
manmade : 0.00%
vegetation : 0.00%
Current val miou is 0.095

**Comment by zhangzw12319** [comment]
Have you made any change to the original code? The reproduced result is uploaded in `./logs/nohup_nusc_val.log` for comparasion.

**Comment by the-king-of-yhq** [comment]
Sorry, that is my error. I use your weight again to get the similar results. But I meet the same problem of NAN again during training the nuscene dataset . Is this related to the original learning rate? Since I set batch to 1 due to memory.

Validation per class PQ, SQ, RQ and IoU: 
             barrier :  57.80%   78.49%   73.63%   74.79%
             bicycle :  51.84%   83.55%   62.05%   31.94%
                 bus :  71.88%   94.65%   75.95%   87.93%
                 car :  92.52%   95.87%   96.51%   92.45%
construction_vehicle :  41.41%   87.59%   47.27%   44.06%
          motorcycle :  75.56%   92.75%   81.47%   75.09%
          pedestrian :  82.26%   89.70%   91.71%   71.17%
        traffic_cone :  80.61%   89.24%   90.32%   55.46%
             trailer :  56.79%   88.66%   64.05%   63.66%
               truck :  70.02%   94.28%   74.26%   83.31%
   driveable_surface :  95.47%   95.48%   99.98%   95.75%
          other_flat :  47.18%   82.17%   57.42%   69.52%
            sidewalk :  60.35%   77.26%   78.11%   70.27%
             terrain :  44.18%   73.50%   60.11%   70.28%
             manmade :  86.05%   87.44%   98.41%   88.81%
          vegetation :  82.53%   85.66%   96.35%   86.40%
PQ 68.5  PQ_dagger  73.9  SQ 87.3  RQ 78.0  |  PQ_th 68.1  SQ_th 89.5  RQ_th 75.7  |  PQ_st 69.3  SQ_st 83.6  RQ_st 81.7  |  mIoU 72.6
Current val PQ is 68.5 while the best val PQ is 69.3
Current val miou is 72.6
epoch 27 iter  4688, avg_loss: 3.9, semantic loss: 0.5, center loss: 0.6, offset loss: 0.1, instmap loss: 0.2, pix loss: 2.7

Validation per class iou: 
barrier : 73.87%
bicycle : 30.26%
bus : 85.22%
car : 90.93%
construction_vehicle : 40.18%
motorcycle : 63.82%
pedestrian : 71.85%
traffic_cone : 56.62%
trailer : 59.59%
truck : 80.91%
driveable_surface : 95.75%
other_flat : 69.47%
sidewalk : 70.26%
terrain : 70.25%
manmade : 88.48%
vegetation : 86.48%
Current val miou is 70.9
epoch: 28   lr: 0.00400

Validation per class PQ, SQ, RQ and IoU: 
             barrier :   0.00%    0.00%    0.00%    0.00%
             bicycle :   0.00%    0.00%    0.00%    0.00%
                 bus :   0.00%    0.00%    0.00%    0.00%
                 car :   0.00%    0.00%    0.00%    0.00%
construction_vehicle :   0.00%    0.00%    0.00%    0.00%
          motorcycle :   0.00%    0.00%    0.00%    0.00%
          pedestrian :   0.00%    0.00%    0.00%    0.00%
        traffic_cone :   0.00%    0.00%    0.00%    0.00%
             trailer :   0.00%    0.00%    0.00%    0.00%
               truck :   0.00%    0.00%    0.00%    0.00%
   driveable_surface :   0.00%    0.00%    0.00%    0.00%
          other_flat :   0.00%    0.00%    0.00%    0.00%
            sidewalk :   0.00%    0.00%    0.00%    0.00%
             terrain :   0.00%    0.00%    0.00%    0.00%
             manmade :   0.00%    0.00%    0.00%    0.00%
          vegetation :   0.00%    0.00%    0.00%    0.00%
PQ 0.0  PQ_dagger  0.0  SQ 0.0  RQ 0.0  |  PQ_th 0.0  SQ_th 0.0  RQ_th 0.0  |  PQ_st 0.0  SQ_st 0.0  RQ_st 0.0  |  mIoU 0.0
Current val PQ is 0.0 while the best val PQ is 69.3
Current val miou is 0.0
epoch 28 iter  4688, avg_loss: nan, semantic loss: 0.5, center loss: 0.9, offset loss: 0.1, instmap loss: 1.4, pix loss: 2.7


 37%|███▋      | 1746/4689 [34:56<57:58,  1.18s/it, sem_loss=0.454, center_loss=0.579, offset_loss=0.0526, instmap_loss=0.184, pix_loss=2.65, avg_loss=3.93]
 37%|███▋      | 1747/4689 [34:56<58:01,  1.18s/it, sem_loss=0.454, center_loss=0.579, offset_loss=0.0526, instmap_loss=0.184, pix_loss=2.65, avg_loss=3.93]
 37%|███▋      | 1747/4689 [34:58<58:01,  1.18s/it, sem_loss=0.455, center_loss=0.586, offset_loss=0.0517, instmap_loss=0.183, pix_loss=2.66, avg_loss=nan] 
 37%|███▋      | 1748/4689 [34:58<57:29,  1.17s/it, sem_loss=0.455, center_loss=0.586, offset_loss=0.0517, instmap_loss=0.183, pix_loss=2.66, avg_loss=nan]

Why the avg_loss is nan suddenly?

**Comment by zhangzw12319** [comment]
Well, my training result at Epoch 28 is as the following:

> Validation per class PQ, SQ, RQ and IoU: 
barrier :  70.29%   82.63%   85.07%   75.88%
bicycle :  71.30%   85.39%   83.51%   47.17%
bus :  84.73%   96.17%   88.10%   90.97%
car :  94.72%   96.63%   98.02%   92.09%
construction_vehicle :  56.42%   85.03%   66.35%   56.56%
motorcycle :  88.51%   93.11%   95.06%   85.33%
pedestrian :  87.40%   90.82%   96.23%   83.32%
traffic_cone :  87.71%   91.61%   95.73%   69.49%
trailer :  65.59%   90.44%   72.52%   73.13%
truck :  78.45%   94.77%   82.78%   81.02%
driveable_surface :  95.71%   95.76%   99.95%   95.99%
other_flat :  54.69%   83.23%   65.71%   73.18%
sidewalk :  65.73%   79.59%   82.59%   72.83%
terrain :  53.50%   77.89%   68.69%   75.36%
manmade :  89.35%   90.06%   99.20%   91.06%
vegetation :  86.48%   88.50%   97.72%   88.88%
PQ 76.911  PQ_dagger  81.259  SQ 88.852  RQ 86.077  |  PQ_th 78.511  SQ_th 90.661  RQ_th 86.337  |  PQ_st 74.245  SQ_st 85.838  RQ_st 85.645  |  mIoU 78.266
Current val PQ is 76.911 while the best val PQ is 77.387
Current val miou is 78.266
epoch 28 iter  2344, avg_loss: 3.119, semantic loss: 0.352, center loss: 0.523, offset loss: 0.043, instmap loss: 0.128, pix loss: 2.108

> Validation per class iou: 
barrier : 76.90%
bicycle : 49.33%
bus : 91.03%
car : 91.68%
construction_vehicle : 59.38%
motorcycle : 64.62%
pedestrian : 84.02%
traffic_cone : 72.78%
trailer : 68.59%
truck : 82.87%
driveable_surface : 96.00%
other_flat : 73.15%
sidewalk : 72.82%
terrain : 75.35%
manmade : 90.74%
vegetation : 89.00%
Current val miou is 77.391

There are differences:
- At Epoch 28 the PQ and mIoU should be higher.
- Even if it is at 68 PQ around, it should not be N/A suddenly.

Here are some suggestions:
- My usual setting is batchsize=2, 8 GPUs (V100 32G or A6000 48G). I've attempted to conduct some experiments when batchsize=1 or to use 3 GPUs for DDP training (usually it is better when node number is $2^n$, ,such as 2, 4, 8,16, otherwise the performance may lower down a bit, _e.g._ 3-5 PQ if I remember correctly), but I've never met with N/A. It's also kind of hard for me to speculate about the reason directly.
- Maybe you can close `pix_fusion: Fasle`, `use_sara: False`, `use_att: False` to get baseline result and open the options again.

**Comment by the-king-of-yhq** [comment]
Sorry,  I use 4 GPUs (A100 40G) and set batch=2, but I can achieve your results. This is my train results:
Validation per class PQ, SQ, RQ and IoU: 
             barrier :  60.66%   78.79%   76.98%   77.13%
             bicycle :  58.93%   85.08%   69.26%   30.27%
                 bus :  76.26%   94.10%   81.04%   87.60%
                 car :  93.70%   96.22%   97.38%   93.99%
construction_vehicle :  47.00%   87.13%   53.95%   49.38%
          motorcycle :  81.49%   92.87%   87.75%   78.91%
          pedestrian :  84.36%   89.76%   93.99%   76.87%
        traffic_cone :  83.94%   89.91%   93.36%   61.07%
             trailer :  56.72%   88.84%   63.85%   67.97%
               truck :  73.84%   94.37%   78.24%   84.54%
   driveable_surface :  95.97%   96.02%   99.95%   96.24%
          other_flat :  50.71%   82.85%   61.20%   71.47%
            sidewalk :  65.27%   78.70%   82.93%   73.06%
             terrain :  50.11%   75.53%   66.34%   73.06%
             manmade :  87.28%   88.56%   98.56%   89.74%
          vegetation :  84.91%   86.52%   98.14%   87.75%
PQ 71.9  PQ_dagger  76.6  SQ 87.8  RQ 81.4  |  PQ_th 71.7  SQ_th 89.7  RQ_th 79.6  |  PQ_st 72.4  SQ_st 84.7  RQ_st 84.5  |  mIoU 74.9
Current val PQ is 71.9 while the best val PQ is 71.9
Current val miou is 74.9
epoch 30 iter  3516, avg_loss: 3.6, semantic loss: 0.4, center loss: 0.6, offset loss: 0.0, instmap loss: 0.2, pix loss: 2.5

Validation per class iou: 
barrier : 75.55%
bicycle : 33.87%
bus : 89.50%
car : 92.59%
construction_vehicle : 49.23%
motorcycle : 81.21%
pedestrian : 77.55%
traffic_cone : 62.76%
trailer : 64.97%
truck : 82.84%
driveable_surface : 96.24%
other_flat : 71.42%
sidewalk : 73.06%
terrain : 73.05%
manmade : 89.36%
vegetation : 87.85%
Current val miou is 75.1

And this is my nuScenes config, **Whether there are incorrect Settings**？
dataset:
    name: nuscenes
    version: v1.0-trainval
    path: /home/nuScenes
    sample_pkl_path: /home/nuScenes/pkl_files
    rotate_aug: True
    flip_aug: True
    max_volume_space: [ 100, 3.1415926, 3 ]
    min_volume_space: [ 0, -3.1415926, -5 ]
    gt_generator:
        sigma: 5
    grid_size: [480,360,32]
    inst_aug:
        if_use: False
        aug_type: contmix
        inst_pkl_path: /home/nuScenes/inst_database_train/inst_database_train_info.pkl
        inst_trans: True # random translation for contmix
        inst_rotate: True
        inst_flip: True
        inst_add: True
    num_worker: 4
    min_points: 15
model:
    pix_fusion: True
    pix_fusion_path: /home/lcps-main/checkpoints/resnet18-5c106cde.pth
    use_sara: True
    use_att: True
    model_load_path: null
    model_save_path: /home/lcps-main/nuscene_ori_b2/nu_8k2b4l.pt
    train_batch_size: 2
    val_batch_size: 2
    learning_rate: 0.004
    LR_MILESTONES: [100, 150,200]
    LR_GAMMA: 0.5
    check_iter: 4000
    max_epoch: 300
    post_proc:
        threshold: 0.1
        nms_kernel: 5
        top_k: 100
    center_loss: MSE
    offset_loss: L1
    center_loss_weight: 100
    offset_loss_weight: 10

**Comment by the-king-of-yhq** [comment]
Look forward to your patient answer, thank you！

**Comment by zhangzw12319** [comment]
It looks right for your given configs.

**Comment by the-king-of-yhq** [comment]
Thank you. But I can not get **your results of PQ 76.91 in 28 epoch**. I only **get PQ 71.9 in 30 epoch as presented in the above**. I also **use 4 GPUs (A100 40G) and set batch=2**.  If the configs file is correct, what is the reason for **this gap**?

**Comment by zhangzw12319** [comment]
> Validation per class iou: 
barrier : 76.76%
bicycle : 42.57%
bus : 85.95%
car : 92.09%
construction_vehicle : 51.04%
motorcycle : 76.59%
pedestrian : 80.36%
traffic_cone : 70.78%
trailer : 67.41%
truck : 81.64%
driveable_surface : 96.28%
other_flat : 71.13%
sidewalk : 73.41%
terrain : 73.68%
manmade : 90.31%
vegetation : 88.21%
Current val miou is 76.1
epoch: 30   lr: 0.00400

> Validation per class PQ, SQ, RQ and IoU: 
             barrier :  69.00%   81.54%   84.62%   78.42%
             bicycle :  69.37%   84.37%   82.22%   45.23%
                 bus :  81.61%   95.70%   85.28%   91.50%
                 car :  94.34%   96.47%   97.79%   93.69%
construction_vehicle :  61.32%   86.60%   70.81%   56.40%
          motorcycle :  85.41%   92.74%   92.10%   83.66%
          pedestrian :  87.44%   90.92%   96.17%   81.24%
        traffic_cone :  87.84%   90.99%   96.53%   68.39%
             trailer :  64.42%   88.59%   72.72%   73.18%
               truck :  78.45%   95.05%   82.54%   85.19%
   driveable_surface :  96.17%   96.18%   99.98%   96.42%
          other_flat :  54.27%   82.82%   65.53%   72.88%
            sidewalk :  67.29%   79.80%   84.32%   74.08%
             terrain :  53.43%   77.78%   68.69%   74.80%
             manmade :  88.63%   89.82%   98.67%   90.67%
          vegetation :  86.68%   87.71%   98.83%   88.69%
PQ 76.6  PQ_dagger  80.8  SQ 88.6  RQ 86.1  |  PQ_th 77.9  SQ_th 90.3  RQ_th 86.1  |  PQ_st 74.4  SQ_st 85.7  RQ_st 86.0  |  mIoU 78.4
Current val PQ is 76.6 while the best val PQ is 76.6
Current val miou is 78.4
epoch 30 iter  3516, avg_loss: 3.2, semantic loss: 0.4, center loss: 0.5, offset loss: 0.0, instmap loss: 0.1, pix loss: 2.2

For fair comparision, I've `git clone` my code in thie repo with your config and train it again on AutoDL A40(48 G x 4) to epoch 30. The aforementioned is my result. You can see that PQ usually slightly fluctuates in different experiments. Also I find that the `mIoU` performance is close between your reproduction and my own reproduction. Maybe you can focus your modifications on panoptic metric parts to see whether there is any issue. 

It is kind of strange if it were true that different GPU device can cause performance gap. For convenince, I suggest that you can use my released weights to resume you experiments and get better results to save time, ratehr than align every potential environmental setting for strange misalignments. The training cost is so large that usually 8*GPUs with 10 days to train 120 Epochs for final results. 

This issue will be closed due to its extra length. If you meet further questions, feel free to open a new issue.

**Comment by zhangzw12319** [comment]
Further,  the choose of 4 GPUs or 8 GPUs makes no obvious performance gap.
